//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomataConstructor.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomataConstructor.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automata constructor.
        /// </summary>
        public static string AutomataConstructor_Name {
            get {
                return ResourceManager.GetString("AutomataConstructor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open automat.
        /// </summary>
        public static string openAutomat {
            get {
                return ResourceManager.GetString("openAutomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open tests.
        /// </summary>
        public static string openTests {
            get {
                return ResourceManager.GetString("openTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save automat.
        /// </summary>
        public static string saveAutomat {
            get {
                return ResourceManager.GetString("saveAutomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save automat as....
        /// </summary>
        public static string saveAutomatAs {
            get {
                return ResourceManager.GetString("saveAutomatAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file with automaton.
        /// </summary>
        public static string Saves_FailedToLoadAutomaton {
            get {
                return ResourceManager.GetString("Saves.FailedToLoadAutomaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load file with tests.
        /// </summary>
        public static string Saves_FailedToLoadTests {
            get {
                return ResourceManager.GetString("Saves.FailedToLoadTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes before closing?.
        /// </summary>
        public static string Saves_Reminder {
            get {
                return ResourceManager.GetString("Saves.Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select automaton file name.
        /// </summary>
        public static string Saves_SelectAutomatonFileName {
            get {
                return ResourceManager.GetString("Saves.SelectAutomatonFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select test file name.
        /// </summary>
        public static string Saves_SelectTestFileName {
            get {
                return ResourceManager.GetString("Saves.SelectTestFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsaved.
        /// </summary>
        public static string Saves_Unsaved {
            get {
                return ResourceManager.GetString("Saves.Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save selected area.
        /// </summary>
        public static string saveSelectedArea {
            get {
                return ResourceManager.GetString("saveSelectedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save tests as....
        /// </summary>
        public static string saveTestsAs {
            get {
                return ResourceManager.GetString("saveTestsAs", resourceCulture);
            }
        }
    }
}
