//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlsLibrary.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlsLibrary.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string _string {
            get {
                return ResourceManager.GetString("string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string addNewTest {
            get {
                return ResourceManager.GetString("addNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automata constructor.
        /// </summary>
        public static string AutomataConstructor_Name {
            get {
                return ResourceManager.GetString("AutomataConstructor.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string debugString {
            get {
                return ResourceManager.GetString("debugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string debugTest {
            get {
                return ResourceManager.GetString("debugTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deterministic finite automaton.
        /// </summary>
        public static string DFA {
            get {
                return ResourceManager.GetString("DFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter transition tokens without any separators.
        /// </summary>
        public static string Editor_TransitionsToolTip {
            get {
                return ResourceManager.GetString("Editor.TransitionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-deterministic finite automaton with epsilon-transitions.
        /// </summary>
        public static string EpsilonNFA {
            get {
                return ResourceManager.GetString("EpsilonNFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid automaton!.
        /// </summary>
        public static string Errors_InvalidAutomaton {
            get {
                return ResourceManager.GetString("Errors.InvalidAutomaton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set accepting state.
        /// </summary>
        public static string Errors_SetAccepting {
            get {
                return ResourceManager.GetString("Errors.SetAccepting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set initial state.
        /// </summary>
        public static string Errors_SetInitial {
            get {
                return ResourceManager.GetString("Errors.SetInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string hide {
            get {
                return ResourceManager.GetString("hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is accept:.
        /// </summary>
        public static string isAccept {
            get {
                return ResourceManager.GetString("isAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is initial:.
        /// </summary>
        public static string isInitial {
            get {
                return ResourceManager.GetString("isInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-deterministic finite automaton.
        /// </summary>
        public static string NFA {
            get {
                return ResourceManager.GetString("NFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No issues found.
        /// </summary>
        public static string noIssuesFound {
            get {
                return ResourceManager.GetString("noIssuesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open test panel.
        /// </summary>
        public static string openTestPanel {
            get {
                return ResourceManager.GetString("openTestPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string removeTest {
            get {
                return ResourceManager.GetString("removeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset debug.
        /// </summary>
        public static string resetDebugString {
            get {
                return ResourceManager.GetString("resetDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result:.
        /// </summary>
        public static string resultDebugString {
            get {
                return ResourceManager.GetString("resultDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string resultFailed {
            get {
                return ResourceManager.GetString("resultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not runned.
        /// </summary>
        public static string resultNotRunned {
            get {
                return ResourceManager.GetString("resultNotRunned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string resultPassed {
            get {
                return ResourceManager.GetString("resultPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run all.
        /// </summary>
        public static string runAllTests {
            get {
                return ResourceManager.GetString("runAllTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string runString {
            get {
                return ResourceManager.GetString("runString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string runTest {
            get {
                return ResourceManager.GetString("runTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tool:.
        /// </summary>
        public static string selectTool {
            get {
                return ResourceManager.GetString("selectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string shouldReject {
            get {
                return ResourceManager.GetString("shouldReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start debug.
        /// </summary>
        public static string startDebugString {
            get {
                return ResourceManager.GetString("startDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string stateName {
            get {
                return ResourceManager.GetString("stateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step.
        /// </summary>
        public static string stepDebugString {
            get {
                return ResourceManager.GetString("stepDebugString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string testResult {
            get {
                return ResourceManager.GetString("testResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to delete states and transitions  (D).
        /// </summary>
        public static string Toolbar_DeleteModeToolTip {
            get {
                return ResourceManager.GetString("Toolbar.DeleteModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to place new states and transitions  (E).
        /// </summary>
        public static string Toolbar_EditModeToolTip {
            get {
                return ResourceManager.GetString("Toolbar.EditModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout states and fill attributes  (S).
        /// </summary>
        public static string Toolbar_SelectModeToolTip {
            get {
                return ResourceManager.GetString("Toolbar.SelectModeToolTip", resourceCulture);
            }
        }
    }
}
